spring.application.name=search

spring.security.user.name=search_user
spring.security.user.password=search_password


opensearch.host.path=localhost
opensearch.host.port=9200
opensearch.host.user.name=read_write_spring_application_user
opensearch.host.password=Spring@Java_Test
opensearch.host.schema=http

opensearch.item.index=part-v1

logging.level.org.springframework.security=DEBUG

spring.redis.host=localhost
spring.redis.port=6379

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
server.port=8087